// <auto-generated />
using System;
using BlockchainClient.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace BlockchainClient.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("C##BLOCKCHAIN")
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("BlockchainClient.Models.Block", b =>
                {
                    b.Property<int>("BlockID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BlockchainID");

                    b.Property<string>("Data");

                    b.Property<string>("Hash");

                    b.Property<int>("Index");

                    b.Property<string>("PreviousHash");

                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("User");

                    b.HasKey("BlockID");

                    b.HasIndex("BlockchainID");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("BlockchainClient.Models.Blockchain", b =>
                {
                    b.Property<int>("BlockchainID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BlockchainName");

                    b.HasKey("BlockchainID");

                    b.ToTable("Blockchains");
                });

            modelBuilder.Entity("BlockchainClient.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Hash");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.Property<string>("UserData");

                    b.HasKey("UserID");

                    b.ToTable("BlockchainUser");
                });

            modelBuilder.Entity("BlockchainClient.Models.Block", b =>
                {
                    b.HasOne("BlockchainClient.Models.Blockchain", "Blockchain")
                        .WithMany("Blocks")
                        .HasForeignKey("BlockchainID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
